name: A workflow to deploy in multiple environments

on:
  workflow_dispatch:
   inputs:
    releaseType:
     description: 'Where to release? (Prod or Dev)'
     required: true
     default: 'Dev'

jobs:
  prod:
   if: github.event.inputs.releaseType == 'Prod'
   uses: satvik-eltropy/github-actions-test/.github/workflows/build&deploy.yml@main
   with:
      env_name: Production
   secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        github-api-token: ${{ secrets.API_TOKEN_GITHUB }}
        argocd-auth-token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
  
  dev:
   if: github.event.inputs.releaseType == 'Dev'
   uses: satvik-eltropy/github-actions-test/.github/workflows/build&deploy.yml@main
   with:
      env_name: Dev
   secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        github-api-token: ${{ secrets.API_TOKEN_GITHUB }}
        argocd-auth-token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        

    
  
