name: Build and push golang image to AWS ECR instance

on:
  workflow_dispatch:
  push:
   branches: 
    - integration_test_multiple_services
   paths-ignore:
    - '.github/workflows/**'
jobs:

  build-and-push:
    name: Build and Push to ECR
    needs: [ check-tests ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: github-actions-test
        
    - name: Run the auth-server
      run: |
        ls
        git branch
        cd semaphore-auth-server
        docker build -t auth-server-image .
        docker run -d -p 8001:8001 --name auth-server auth-server-image
        
    - name: Run the integration tests for the application
      run: |
        ls
        cd semaphore-web-server
        go test -tags integration
