name: Build and push golang image to AWS ECR instance

on:
  push:
   branch: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.19/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

    - name: Earthly build docker image
      run: earthly +docker

    -name: Tag image
      run: "docker tag go-example:latest 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:latest"

    - name: Push the Image to Amazon ECR
      run:  "docker push 287241598491.dkr.ecr.us-west-2.amazonaws.com/application-build-docker-images:latest"
      
