name: Multiple service integration testing

on:
  workflow_dispatch:
  push:
   branches: 
    - integration_test_multiple_services
jobs:

  build-and-push:
    name: Build image for integration testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: github-actions-test
        
    - name: Run the auth-server
      run: |
        ls
        cd github-actions-test
        ls
        cd auth-server
        ls
        docker build -t auth-server-image .
        docker run -d -p 8001:8001 --name auth-server auth-server-image
        
    - name: Run the integration tests for the application
      run: |
        ls
        cd github-actions-test/web-server
        go test -tags integration -v
