name: Run unit tests in go
on:
  workflow_call:
    inputs:
     GO_VERSION:
     type: string

jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: Tests for main.go
        run: go test -v 