name: Run unit tests in go
on:
  workflow_call:
env:
  GO_VERSION: 1.15.x
  
jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Tests for main.go
        run: go test -v 
